services:
  bot:
    profiles: !reset []
    restart: unless-stopped
    environment:
      PUBLIC_DASHBOARD_URL: ${PUBLIC_DASHBOARD_URL:-https://example.com}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-https://example.com}

  dashboard:
    profiles: !reset []
    restart: unless-stopped
    ports: !reset []
    environment:
      PUBLIC_DASHBOARD_URL: ${PUBLIC_DASHBOARD_URL:-https://example.com}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-https://example.com}

  postgres:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  voicevox:
    restart: unless-stopped

  backup:
    profiles:
      - maintenance
